# Generated by Django 3.1.6 on 2021-08-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_auto_20210808_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
