# Generated by Django 3.1.6 on 2021-08-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishing_house',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='PublishingHouse',
        ),
    ]
